### PR TITLE
Edited ytdl-core dependency

### PR DESCRIPTION
**Pull request by remigranotier**
Related to https://github.com/krawthekrow/pi-connect-maker/issues/5, I couldn't use the youtube feature as well. By following this [stackoverflow post](https://stackoverflow.com/questions/78743288/403-forbidden-when-using-ytdl-core), updating `ytdl-core` to `@distube/ytdl-core` fixed the issue on my end. It seems `ytdl-core` is no longer maintained.

### CODE REVIEW

**Comment by krawthekrow** [comment]
Thanks! My impression is that ytdl is still being maintained, just really slowly. Fine to move to the distube fork. I see a bunch of auto formatting changes and extra logging though, would you be able to exclude those from the change? I'd be fine with adding auto-formatting but it would be a separate task to make it a true dependency.

**Comment by remigranotier** [comment]
Indeed, didn't notice. Fixed it now!

**Comment by remigranotier** [comment]
Struggled a bit with editor but now fixed! Didn't notice, thank you

**Comment by krawthekrow** [comment]
Thanks!

**Pull request merged**
